spring.application.name=finance
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=particular_databaseUrl
spring.datasource.username=username
spring.datasource.password=pass

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=Your_secrete_key
jwt.expiration=1800000 //30mins

