spring.application.name=finance
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/Finance
spring.datasource.username=postgres
spring.datasource.password=2006

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=MGo4NqogMknImRe2qUfZ5IphvwRYe8awh+IuqxJaD6JitvQGWJ2nvTFewZs3OcsKvP9aBeVtD+XJx7LPdJU3UQ==
jwt.expiration=1800000 //30minutes
twilio.account.sid=ACb71c88df8a4ab2d8a19aeca582a2b2a7
twilio.auth.token=f2aa791df225c040b6379fcd5a0b6e73
twilio.phone.number=+19302122808
