spring.application.name=finance
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=Enter_Url_Based_on_the_database
spring.datasource.username=User_Name
spring.datasource.password=PASS_word

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=use_your_own key
jwt.expiration=1800000 //30minutes

